# Generated by Django 5.1.1 on 2024-09-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_user_is_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
    ]
