# Generated by Django 5.1.1 on 2024-09-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_remove_user_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='collection_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
