# Generated by Django 5.1.1 on 2024-09-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_upload_collection_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='collection_name',
        ),
    ]
