# Generated by Django 5.1.1 on 2024-09-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_remove_upload_collection_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='collection_name',
            field=models.CharField(default='collection', max_length=100),
        ),
    ]
