# Generated by Django 5.1.1 on 2024-09-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_alter_upload_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_name',
            field=models.FileField(null=True, upload_to='./document/'),
        ),
    ]
