# Generated by Django 5.1.1 on 2024-09-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0019_userredishistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='description',
            field=models.CharField(default='collection_description', max_length=100),
        ),
        migrations.AddField(
            model_name='upload',
            name='title',
            field=models.CharField(default='collection_title', max_length=100),
        ),
        migrations.AlterField(
            model_name='userredishistory',
            name='redis_key',
            field=models.CharField(default='3ff674e7-4123-41cd-a18f-80fb6eb3d01b', max_length=255, unique=True),
        ),
    ]
