# Generated by Django 5.1.1 on 2024-10-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0020_upload_description_upload_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='userredishistory',
            name='redis_key',
            field=models.CharField(default='5aa25564-a42e-4a19-9c88-fb23543212c1', max_length=255, unique=True),
        ),
    ]
